language: php

php:
  - 7.0

install:
  - npm install -g snyk

before_script:
  - composer self-update
  - composer install
  - phpenv rehash

script:
  - snyk test

after_script:
  - snyk monitor --org=engineering-wdc
