language: php

php:
  - 5.3
  - 5.4
  - 5.5

install:
  - npm install -g snyk

before_script:
  - composer self-update
  - composer install
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - snyk test
  - phpcs --standard=psr2 src/
  - phpunit --coverage-text

after_script:
  - snyk monitor --org=engineering-wdc
