sudo: false
language: php

install:
  - npm install -g snyk

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
 
matrix:
    allow_failures:
        - php: hhvm

before_script:
  - composer self-update
  - composer install
  - phpenv rehash

script:
  - phpunit --coverage-text
  - snyk test

after_script:
  - snyk monitor --org=engineering-wdc
